"""Crear tabla users

Revision ID: bb784f3cc4fd
Revises: 
Create Date: 2024-10-18 05:19:53.707764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb784f3cc4fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('matricula', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=150), nullable=False),
    sa.Column('apellido_paterno', sa.String(length=150), nullable=False),
    sa.Column('apellido_materno', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=15), nullable=False),
    sa.Column('correo_electronico', sa.String(length=150), nullable=False),
    sa.Column('antiguedad_anos', sa.Integer(), nullable=False),
    sa.Column('antiguedad_quincenas', sa.Integer(), nullable=False),
    sa.Column('antiguedad_dias', sa.Integer(), nullable=False),
    sa.Column('dias_descanso', sa.String(length=200), nullable=True),
    sa.Column('placas', sa.String(length=10), nullable=False),
    sa.Column('marca_vehiculo', sa.String(length=100), nullable=False),
    sa.Column('modelo_vehiculo', sa.String(length=100), nullable=False),
    sa.Column('tarjeton_pago', sa.String(length=200), nullable=False),
    sa.Column('licencia_manejo', sa.String(length=200), nullable=False),
    sa.Column('tarjeta_circulacion', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('matricula'),
    sa.UniqueConstraint('correo_electronico')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
